name: Build Resumé and release

on: [push]

jobs:
  build_and_release_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build templates
        run: npm run build

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume-ptbr.tex

      - name: Move pdf to resume folder
        run: |
          mkdir -p build/pt
          mv resume-ptbr.pdf build/phelipe-teles-resume-ptbr.pdf
          mv resume-ptbr.json build/phelipe-teles-resume-ptbr.json

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: build
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
