name: Build Resumé and release

on: [push]

jobs:
  build_and_release_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            phelipe-teles-resume-ptbr.tex
            phelipe-teles-resume-en.tex

      - name: Move pdf to resume folder
        run: |
          mkdir build
          mv phelipe-teles-resume-ptbr.pdf build
          mv phelipe-teles-resume-en.pdf build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: build
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
